# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mbcb_cpp <- function(p_0, p_1, tau_hat, sample_weight) {
    .Call(`_iteval_mbcb_cpp`, p_0, p_1, tau_hat, sample_weight)
}

